- action:
    module: ec2_remote_facts
    region: "{{ region }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    filters:
      instance-state-name: running
      "tag:Name": "{{ group_web }}"
  register: ec2_facts

# - action:
#     module: debug
#     msg: "{{ item }}"
#   with_items: "{{ ec2_facts.instances }}"

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip_address }}"
    groupname: launched
  with_items: "{{ ec2_facts.instances }}"