- name: Create security group webserver
  ec2_group:
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    region: "{{ region }}"
    name: "{{ sg_ssh }}"
    description: security group websiteinstance
    rules:
      - proto: tcp  
        from_port: 22  
        to_port: 22  
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all  
        cidr_ip: 0.0.0.0/0

- name: Create security group HTTP 0.0.0.0
  ec2_group:
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    region: "{{ region }}"
    name: "{{ sg_web }}"
    description: security group websiteinstance
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all  
        cidr_ip: 0.0.0.0/0