- name: Configure the webservers
  hosts: localhost
  remote_user: "{{ ec2_user }}"
  gather_facts: True

  vars_files:
    - vars/aws-creds.yml
    - vars/def_vars.yml

  roles:
    - get_instances

- name: Configure the webservers
  hosts: launched
  remote_user: "{{ ec2_user }}"
  become: True
  gather_facts: True

  vars_files:
    - vars/aws-creds.yml
    - vars/def_vars.yml
    - vars/git-creds.yml

  roles:
    - clone_proyect_w_req

  tasks:
    - name: Restart Supervisor
      supervisorctl: name={{ application_name }} state=restarted
      notify:
      - restart nginx